/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cognitive_Quest_predict_pattern_perform;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author WIn
 */

public class NGG extends javax.swing.JFrame {

    int random=(int) (Math.random()*100 + 1); 
    int guessratio = 1;
    int remainguess = 10;
      
    String score1="";
    String rguess="";
      
    private JFrame frame;
    public NGG() {
        initComponents();
        
         setDefaultCloseOperation(frame.DO_NOTHING_ON_CLOSE);
    addWindowListener(new WindowAdapter(){
        public void windowClosing(WindowEvent e){
            if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit Cognitive Quest","Warning - Cognitive Quest",
            JOptionPane.YES_NO_OPTION )== JOptionPane.YES_NO_OPTION)
    {
        System.exit(0);
        }
        }
    });
    
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lb7 = new javax.swing.JLabel();
        lb8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        lb4 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lb6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();
        jRadioButton29 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton31 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to Number Guessing Game");
        setMinimumSize(new java.awt.Dimension(600, 300));
        setPreferredSize(new java.awt.Dimension(600, 485));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 0, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NUMBER GUESSING GAME");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 20, 490, 70);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("-> Enter a number between 1 to 100 only || You have total 10 chances");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 70, 540, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 0, 550, 110);

        lb7.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 18)); // NOI18N
        lb7.setForeground(new java.awt.Color(255, 255, 51));
        lb7.setText("Hint Instructions - ");
        getContentPane().add(lb7);
        lb7.setBounds(10, 300, 320, 23);

        lb8.setBackground(new java.awt.Color(0, 255, 255));
        lb8.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 14)); // NOI18N
        lb8.setForeground(new java.awt.Color(255, 255, 255));
        lb8.setText("1.For difference b/w your and actual number > 50 --> Too Far! ");
        getContentPane().add(lb8);
        lb8.setBounds(10, 320, 560, 18);

        jLabel9.setBackground(new java.awt.Color(0, 255, 255));
        jLabel9.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("2.For difference b/w your and actual number <= 50 --> Quite Far! ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 340, 570, 18);

        jLabel10.setBackground(new java.awt.Color(0, 255, 255));
        jLabel10.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("3.For difference b/w your and actual number <= 40 --> Little Far! ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 360, 570, 18);

        jLabel11.setBackground(new java.awt.Color(0, 255, 255));
        jLabel11.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("4.For difference b/w your and actual number <= 30 --> Little Close! ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 380, 580, 18);

        jLabel12.setBackground(new java.awt.Color(0, 255, 255));
        jLabel12.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("5.For difference b/w your and actual number <= 20 --> Quite Close! ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 400, 590, 18);

        jLabel13.setBackground(new java.awt.Color(0, 255, 255));
        jLabel13.setFont(new java.awt.Font("MS Reference Sans Serif", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("6.For difference b/w your and actual number <= 10 --> Too Close! ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 420, 580, 18);

        b1.setBackground(new java.awt.Color(255, 102, 102));
        b1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b1.setText("GUESS");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(210, 230, 80, 40);

        t1.setEditable(false);
        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(90, 150, 70, 50);

        t2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t2.setName(""); // NOI18N
        getContentPane().add(t2);
        t2.setBounds(220, 150, 70, 50);

        t3.setEditable(false);
        t3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3);
        t3.setBounds(340, 150, 70, 50);

        lb4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lb4.setForeground(new java.awt.Color(0, 255, 255));
        lb4.setText("Enter Your Guess");
        getContentPane().add(lb4);
        lb4.setBounds(200, 210, 130, 16);

        lb3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lb3.setForeground(new java.awt.Color(0, 255, 255));
        lb3.setText("Remaining Attempts");
        getContentPane().add(lb3);
        lb3.setBounds(60, 210, 150, 16);

        lb5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lb5.setForeground(new java.awt.Color(0, 255, 255));
        lb5.setText("Final Score");
        getContentPane().add(lb5);
        lb5.setBounds(340, 210, 100, 16);

        b2.setBackground(new java.awt.Color(102, 255, 102));
        b2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b2.setText("Give Up!");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(460, 120, 110, 40);

        b3.setBackground(new java.awt.Color(51, 255, 255));
        b3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b3.setText("Play Again");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(460, 170, 110, 40);

        jButton4.setBackground(new java.awt.Color(255, 255, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("HOME");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(460, 220, 110, 40);

        lb6.setBackground(new java.awt.Color(153, 255, 255));
        lb6.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        lb6.setText("Go...Go...Go...Guess...Guess...Guesss....");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb6, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 280, 600, 20);

        jRadioButton1.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton1.setToolTipText("");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(390, 240, 20, 20);

        jRadioButton2.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton2.setForeground(new java.awt.Color(255, 0, 51));
        jRadioButton2.setToolTipText("");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(300, 240, 20, 20);

        jRadioButton3.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton3.setToolTipText("");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(330, 240, 20, 20);

        jRadioButton4.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton4.setToolTipText("");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(360, 240, 20, 20);

        jRadioButton5.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton5.setToolTipText("");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(180, 240, 20, 20);

        jRadioButton6.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton6.setToolTipText("");
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(150, 240, 20, 20);

        jRadioButton7.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton7.setToolTipText("");
        getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(120, 240, 20, 20);

        jRadioButton8.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton8.setToolTipText("");
        getContentPane().add(jRadioButton8);
        jRadioButton8.setBounds(420, 240, 20, 20);

        jRadioButton9.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton9.setToolTipText("");
        getContentPane().add(jRadioButton9);
        jRadioButton9.setBounds(90, 240, 20, 20);

        jRadioButton10.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton10.setToolTipText("");
        getContentPane().add(jRadioButton10);
        jRadioButton10.setBounds(60, 240, 20, 20);

        jRadioButton11.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton11.setToolTipText("");
        getContentPane().add(jRadioButton11);
        jRadioButton11.setBounds(30, 210, 20, 20);

        jRadioButton12.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton12.setToolTipText("");
        getContentPane().add(jRadioButton12);
        jRadioButton12.setBounds(30, 240, 20, 20);

        jRadioButton14.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton14.setToolTipText("");
        getContentPane().add(jRadioButton14);
        jRadioButton14.setBounds(30, 180, 20, 20);

        jRadioButton15.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton15.setToolTipText("");
        getContentPane().add(jRadioButton15);
        jRadioButton15.setBounds(30, 120, 20, 20);

        jRadioButton16.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton16.setToolTipText("");
        getContentPane().add(jRadioButton16);
        jRadioButton16.setBounds(30, 150, 20, 20);

        jRadioButton13.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton13.setToolTipText("");
        getContentPane().add(jRadioButton13);
        jRadioButton13.setBounds(60, 120, 20, 20);

        jRadioButton17.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton17.setToolTipText("");
        getContentPane().add(jRadioButton17);
        jRadioButton17.setBounds(90, 120, 20, 20);

        jRadioButton18.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton18.setToolTipText("");
        getContentPane().add(jRadioButton18);
        jRadioButton18.setBounds(120, 120, 20, 20);

        jRadioButton19.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton19.setToolTipText("");
        getContentPane().add(jRadioButton19);
        jRadioButton19.setBounds(150, 120, 20, 20);

        jRadioButton20.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton20.setToolTipText("");
        getContentPane().add(jRadioButton20);
        jRadioButton20.setBounds(180, 120, 20, 20);

        jRadioButton21.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton21.setToolTipText("");
        getContentPane().add(jRadioButton21);
        jRadioButton21.setBounds(210, 120, 20, 20);

        jRadioButton22.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton22.setToolTipText("");
        getContentPane().add(jRadioButton22);
        jRadioButton22.setBounds(240, 120, 20, 20);

        jRadioButton23.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton23.setToolTipText("");
        getContentPane().add(jRadioButton23);
        jRadioButton23.setBounds(270, 120, 20, 20);

        jRadioButton24.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton24.setToolTipText("");
        getContentPane().add(jRadioButton24);
        jRadioButton24.setBounds(300, 120, 20, 20);

        jRadioButton25.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton25.setToolTipText("");
        getContentPane().add(jRadioButton25);
        jRadioButton25.setBounds(330, 120, 20, 20);

        jRadioButton26.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton26.setToolTipText("");
        getContentPane().add(jRadioButton26);
        jRadioButton26.setBounds(360, 120, 20, 20);

        jRadioButton27.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton27.setToolTipText("");
        getContentPane().add(jRadioButton27);
        jRadioButton27.setBounds(390, 120, 20, 20);

        jRadioButton28.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton28.setToolTipText("");
        getContentPane().add(jRadioButton28);
        jRadioButton28.setBounds(420, 120, 20, 20);

        jRadioButton29.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton29.setToolTipText("");
        getContentPane().add(jRadioButton29);
        jRadioButton29.setBounds(420, 150, 20, 20);

        jRadioButton30.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton30.setToolTipText("");
        getContentPane().add(jRadioButton30);
        jRadioButton30.setBounds(420, 180, 20, 20);

        jRadioButton31.setBackground(new java.awt.Color(153, 255, 255));
        jRadioButton31.setToolTipText("");
        getContentPane().add(jRadioButton31);
        jRadioButton31.setBounds(420, 210, 20, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cognitive_Quest_predict_pattern_perform/ngg_back.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMinimumSize(new java.awt.Dimension(600, 500));
        jLabel1.setPreferredSize(new java.awt.Dimension(600, 500));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 450);

        getAccessibleContext().setAccessibleName("Number Guessing Game");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        OptionPage op = new OptionPage();
        op.show();
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here
      int user = Integer.parseInt(t2.getText());
        
            if(user>100 || user<0)
      {
        lb6.setText("You Lose!!! You had to enter a number between 1 to 100 only.");
        
        
        t2.setEditable(false);
          b1.setEnabled(false);
          b2.setEnabled(false);
          t3.setText("  ---");
            
      }
            
      else if (user == random)
      {
          lb6.setText("Your guessing is correct!! The number is "+random);
          int score = (remainguess*10);
          score1 = Integer.toString(score);
          t3.setText(score1);
          t2.setEditable(false);
          b1.setEnabled(false);
          b2.setEnabled(false);
      }
      else if (user > random)
      {
          
            if(user-random<=10)
            {
                lb6.setText("Too close!!!   GO LOWER SIDE   Keep trying.... ");
            }
            else if(user-random<=20)
            {
                lb6.setText("Quite close!!!   GO LOWER SIDE   Keep trying.... ");
            }
            else if(user-random<=30)
            {
                lb6.setText("Little close!!!   GO LOWER SIDE   Keep trying.... ");
            }
            else if(user-random<=40)
            {
                lb6.setText("Little Far!!!  GO LOWER SIDE   Keep trying.... ");
            }
            else if(user-random<=50)
            {
                lb6.setText("Quite Far!!!   GO LOWER SIDE   Keep trying.... ");
            }
            else if(user-random>50)
            {
                lb6.setText("Too Far!!!   GO LOWER SIDE   Keep trying.... ");
            }
      }
       else if (user < random)
      {
          
            if(random-user<=10)
            {
                lb6.setText("Too close!!!   GO HIGHER SIDE.   Keep trying....");
            }
            else if(random-user<=20)
            {
                lb6.setText("Quite close!!!   GO HIGHER SIDE.   Keep trying....");
            }
            else if(random-user<=30)
            {
                lb6.setText("Little close!!!   GO HIGHER SIDE.     Keep trying....");
            }
            else if(random-user<=40)
            {
                lb6.setText("Little Far!!!   GO HIGHER SIDE.   Keep trying....");
            }
            else if(random-user<=50)
            {
                lb6.setText("Quite Far!!!   GO HIGHER SIDE.   Keep trying....");
            }
            else if(random-user>50)
            {
                lb6.setText("Too Far!!!   GO HIGHER SIDE.   Keep trying....");
            }
      }
            else
      {
        lb6.setText("You Lose!!! You had to enter a number between 1 to 100 only.");
        
      }
        remainguess = 10 - guessratio;
        rguess = Integer.toString(remainguess);
          t1.setText(  rguess);
          guessratio++;    
          if (guessratio==11)
        {
            lb6.setText("You Lose!!!  Start Again...  The number is "+random);
        t2.setEditable(false);
          b1.setEnabled(false);
          b2.setEnabled(false);
          t3.setText("0 ");
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        lb6.setText("Ohh! You Give Up.  The number is "+random);
        t2.setEditable(false);
        b1.setEnabled(false);
        b2.setEnabled(false);
        t3.setText("0 ");
       
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        lb6.setText("Go...Go...Go...Guess...Guess...Guesss....");
        b1.setEnabled(true);
        b2.setEnabled(true);
        t2.setEditable(true);
        t1.setText("");
        t2.setText("");
        t3.setText("");
        random=(int) (Math.random()*100 + 1); 
        guessratio = 1;
        remainguess = 10;
    }//GEN-LAST:event_b3ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NGG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NGG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NGG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NGG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NGG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton29;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton31;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JLabel lb8;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
